### ISSUE TITLE
What is this about?

### ISSUE THREAD

**Issue by sendsms** [fortinet-solutions-cse/ansible_fgt_modules#1]
Hi, 

Came across this project. Wondering is this fortigate modules for ansible? Is there any documents describing the project? 

Thanks.

**Comment by sendsms** [comment]
> Hi @sendsms,
> this is a temporary repository where we place the modules generated automatically by https://github.com/fortinet-solutions-cse/ansible_generator. This is just a temporary location and probably will be removed shortly.

Thanks for your reply. 

So ansible_generator will generate many ansible module automatically? I tried run it but it complaints missing fgt_schema.json file.

**Comment by mamunozgonzalez** [comment]
Yes, it will generate every ansible module for FGT. It needs fgt_schema.json file that you can obtain with a rest api call: GET [http://{{fgt_ip}}/api/v2/cmdb?action=schema](http://{{fgt_ip}}/api/v2/cmdb?action=schema) (just download the content into a file with that name)
We use this to help us create the Ansible modules. After proper review, testing and adjustments they are submitted to Ansible Core. You can see the output created by this tool in this repository, under 'v6.0.2' directory.

**Comment by haodeon** [comment]
Hi @mamunozgonzalez,
I'd like to give these modules in the v.6.0.2 directory a test. Should I expect simple operations like setting interfaces properties to work?
Are the modules idempotent?

**Comment by mamunozgonzalez** [comment]
Hi @haodeon ,
 sure, you can test them but please take into account that we have only tested a few of them. This is the output of a generator and sometimes they need to be adjusted before use. Those which pass the tests are uploaded to ansible and are now in process of being included into the official distro. So, the answer is yes to both questions but there may be exceptions. My advice is handle with care :)

**Comment by haodeon** [comment]
I would be testing these modules against some fresh virtual machines in Azure deployed using the PAYG method. So there would be no harm or adverse issues with just deleting the machines afterwards.
I've converted the HA ports ARM template to Terraform and when I want to play with some Fortigates I just run terraform to create a test network.

**Comment by mamunozgonzalez** [comment]
That's great. Please let us know the result and feel free to contribute your examples. I'm keeping a list of working examples for the modules that I am testing in: 
https://github.com/fortinet-solutions-cse/ansible_generator/tree/master/examples
This folder can also give you an idea of the modules we have tested already.
