### ISSUE TITLE
How to use these playbooks?

### ISSUE THREAD

**Issue by LZhipeng** [fortinet-solutions-cse/ansible_fgt_modules#15]
Hi,
Could these playbook run successfully under v6.0.2/xxx/?
I run several playbook in my environment and all failed as following error:
~/Downloads/ansible_fgt_modules-master$ ansible-playbook v6.0.2/user/fortios_user_adgrp_example.yml 

PLAY [localhost] ********************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************
ok: [localhost]

TASK [Configure FSSO groups.] *******************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: Attempted relative import in non-package
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/lzp/.ansible/tmp/ansible-tmp-1561361170.31-123435029040815/AnsiballZ_fortios_user_adgrp.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/home/lzp/.ansible/tmp/ansible-tmp-1561361170.31-123435029040815/AnsiballZ_fortios_user_adgrp.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/lzp/.ansible/tmp/ansible-tmp-1561361170.31-123435029040815/AnsiballZ_fortios_user_adgrp.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_fortios_user_adgrp_payload_LKpEvN/__main__.py\", line 260, in <module>\n  File \"/tmp/ansible_fortios_user_adgrp_payload_LKpEvN/__main__.py\", line 245, in main\n  File \"/home/lzp/Downloads/fortiosapi-master/fortiosapi/fortiosapi.py\", line 40, in <module>\n    from .exceptions import (InvalidLicense, NotLogged)\nValueError: Attempted relative import in non-package\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP **************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

What's wrong with my test?

Thanks,
Li Zhipeng

**Comment by mamunozgonzalez** [comment]
Hi @LZhipeng 
Do you have a valid license in your fortigate? I see one of the logs is reporting that fortiosapi (the library used by our modules) can't log in bcs of invalid license.

Can you please check this out and let us know the result?

**Comment by LZhipeng** [comment]
My license is valid.
After I modifi the https as True in playbook the result become:
~/Downloads/ansible_fgt_modules-master/v6.0.2/user$ ansible-playbook fortios_user_adgrp_example.yml 

PLAY [localhost] ********************************************************************************************

TASK [Gathering Facts] **************************************************************************************
ok: [localhost]

TASK [Configure FSSO groups.] *******************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "meta": {"build": 866, "error": -173, "http_method": "POST", "http_status": 500, "name": "adgrp", "path": "user", "revision": "1.0.1.9647256268493331860.1561536094", "serial": "FGVM1VTM19000634", "status": "error", "vdom": "root", "version": "v6.2.0"}, "msg": "Error in repo"}

PLAY RECAP **************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by mamunozgonzalez** [comment]
Hi @LZhipeng 
 the examples that you see here are just for reference and must be filled with your own data. If you want ready-to-run examples please use the ones in: 

https://github.com/fortinet-solutions-cse/ansible_generator/tree/master/examples

Since we are also following up this conversation via mail I'm closing this ticket to avoid duplicate channels.
