### ISSUE TITLE
Use loop in : fortios_vpn_ssl_web_portal_example.yml

### ISSUE THREAD

**Issue by vingertop** [fortinet-solutions-cse/ansible_fgt_modules#17]
Hi, 
I'm trying to use this module in Ansible 2.8 to add RDP bookmarks to an ssl vpn portal.

- hosts: localhost
  vars:
   host: "xxx"
   username: "xxx"
   password: "xxx"
   vdom: "root"
  tasks:
  - name: Portal URL's
    fortios_vpn_ssl_web_portal:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "true"
      vpn_ssl_web_portal:
        state: "present"
        bookmark-group:
         -
           bookmarks:
            -
               apptype: "{{ item.apptype }}"
               host: " {{ item.host }}"
               name: "{{ item.name }}"
               port: "{{ item.port }}"
               security: "{{ item.security }}"
            -
               apptype: "rdp"
               host: "2.3.4.5"
               name: "TEST3"
               port: "3389"
               security: "rdp"
           name: "gui-bookmarks"
        name: "ssl-vpn-portal-test"
    loop:
      - { apptype: "rdp", host: "1.2.3.4", name: "TEST2", port: "3389", security: "any" }
      - { apptype: "rdp", host: "1.2.3.5", name: "ATEST2", port: "3389", security: "any" }

> 

Output :

`PLAY [localhost] ****************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Portal URL's] *************************************************************************************************************************************************************************************************************************
changed: [localhost] => (item={'apptype': 'rdp', 'name': 'TEST2', 'security': 'any', 'port': '3389', 'host': '1.2.3.4'})
changed: [localhost] => (item={'apptype': 'rdp', 'name': 'ATEST2', 'security': 'any', 'port': '3389', 'host': '1.2.3.5'})

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0`

It will only add ATEST2 and TEST3 as bookmarks. TEST2 is disregarded or overwritten by de last entry in the loop list. Also when the complete list of bookmarks is not in the playbook it will overwrite the list present, it does not seem to be idempotent.

**Comment by mamunozgonzalez** [comment]
Hi @vingertop ,
 yes, the behaviour is correct. The last iteration of the loop is asking Ansible to set bookmarks to ATEST2 and TEST3, overwriting all the previous content for that bookmarks attribute.

Please note that "bookmarks" is on second level of nesting in the hierarchy. The behaviour you expect can only be achieved with first level attributes where you have a way to specify 'state:present/absent'. As you can see there is no 'state: present/absent' for bookmarks attribute, only for 'vpn_ssl_web_portal'.

**Comment by vingertop** [comment]
OK, I understand, thanks for your fast response 👍 
So there is no way to use a loop to add bookmarks, 
I need to maintain the complete list in the bookmarks table.
In this case I will automate/script the playbook creation itself to reflect bookmark lists.
This will provide me with a timely and suitable workaround.
__

I could not help seeing this module in the docs :
https://github.com/ftntcorecse/ftnt-ansible-docs/blob/master/docs/fortios_playbooks/fortios_vpn.ssl.web_user_group_bookmark.rst

It seems it is not yet available using Ansible 2.8.2 with fortiosapi 0.10.8.
Will this module be available ? 
Will the behaviour be the same in this module ?

**Comment by mamunozgonzalez** [comment]
Right, you are correct.

Regarding the module you asked for, I think you can find it here:

https://github.com/fortinet-solutions-cse/ansible_fgt_modules/tree/master/v6.0.5/vpn_ssl_web
https://github.com/fortinet-solutions-cse/ansible_fgt_modules/tree/master/legacy-v6.0.2/vpn_ssl_web

You can download/clone this repo and use the modules directly (e.g. by setting the var export ANSIBLE_LIBRARY=path of your module).


(note the difference between 6.0.5 and legacy-6.0.2, aside from the fgt sw version is that the new ones add support for HTTPAPI, come with unit tests and also include some other suggestions coming from Ansible reviews, such as using always underscores instead of hyphens)
