### ISSUE TITLE
Module missing? POST: system/vmlicense/upload/

### ISSUE THREAD

**Issue by JonTheNiceGuy** [fortinet-solutions-cse/ansible_fgt_modules#2]
I approached our SE last year to find out how I could push a license to a box, and evenutally he said:
> The below is from the API doc with regards to the REST API and uploading a VM licence. 

And then provided this snip:
![image](https://user-images.githubusercontent.com/228671/50002972-deedb680-ff99-11e8-8c5d-daa870f8b035.png)

I've been unable to find this document, however, from the content here I think the following gist should provide this feature? https://gist.github.com/JonTheNiceGuy/b697e6546812a001e65236d45e41667d

**Comment by mamunozgonzalez** [comment]
Hi @JonTheNiceGuy ,

have you tried this example?
https://github.com/fortinet-solutions-cse/40ansible/blob/master/examples/fortigate_upload_license.yml

**Comment by thomnico** [comment]
Please share the version of your Fortigate ...

**Comment by JonTheNiceGuy** [comment]
@thomnico : Azure BYOL FortiGate 6.0.3 Single Gateway
@mamunozgonzalez : I hadn't, but that certainly seems easier than my version!!

**Comment by mamunozgonzalez** [comment]
I closing this one since license upload has to be done using fortiosconfig in 40ansible repository: https://github.com/fortinet-solutions-cse/40ansible/blob/master/examples/fortigate_upload_license.yml
