### ISSUE TITLE
Changing order for existing policies.

### ISSUE THREAD

**Issue by mbranchnl** [fortinet-solutions-cse/ansible_fgt_modules#21]
The fortios_firewall_policy works fine for adding or removing policies but i can't find the procedure to change the ordering of existing firewall rules (with preserving of the Policy ID).

Is the module in any way useable to change the order of firewall policies?

Kind regards,

**Comment by mamunozgonzalez** [comment]
Hi  @mbranchnl ,
For moving policies we have another module. Please check this example on how to use it:

https://github.com/fortinet-solutions-cse/40ansible/blob/e2a663dbd535671600e56d64ddc0c465b88991e4/library/fortiosconfig.py#L75

It belongs to 'fortiosconfig' module, located in 40ansible repo in this github account (https://github.com/fortinet-solutions-cse/40ansible).

Hope that helps,
Best Regards.
