### ISSUE TITLE
IPSec Phase 1 and 2 proposals only allow weak ciphers

### ISSUE THREAD

**Issue by sbraz** [fortinet-solutions-cse/ansible_fgt_modules#24]
Hi,
For some reason only weak proposals are allowed by the modules, for instance:
https://github.com/fortinet-solutions-cse/ansible_fgt_modules/blob/dfed70ded3e3ec5dc103831cb8130b926a2885d0/v6.0.6/vpn_ipsec/fortios_vpn_ipsec_phase1_interface.py#L1420-L1422
https://github.com/fortinet-solutions-cse/ansible_fgt_modules/blob/dfed70ded3e3ec5dc103831cb8130b926a2885d0/v6.0.6/vpn_ipsec/fortios_vpn_ipsec_phase2_interface.py#L639-L643

**Comment by chillancezen** [comment]
hi Louis, 

there are 62 proposals for users to choose. 
module `fortios_vpn_ipsec_phase2_interface` has the fix on 2.10/devel branch: https://github.com/ansible/ansible/pull/64767

I will prepare another patch to address module `fortios_vpn_ipsec_phase1_interface`'s proposal soon. 

thanks,
Link
