### ISSUE TITLE
Unsupported Proposals on Phase1 and Phase2 interface configuration

### ISSUE THREAD

**Issue by shariaty59** [fortinet-solutions-cse/ansible_fgt_modules#30]
Hi, Looking at the Ansible Network Modules documentation on [phase1](https://docs.ansible.com/ansible/latest/modules/fortios_vpn_ipsec_phase1_interface_module.html#fortios-vpn-ipsec-phase1-interface-module) and [phase2](https://docs.ansible.com/ansible/latest/modules/fortios_vpn_ipsec_phase2_interface_module.html#fortios-vpn-ipsec-phase2-interface-module) interface configuration, the only choices are null and DES only! No 3DES or AES Flavors on any phase1 and phase2 proposals are supported. Please advise on how I can make it work with those settings. Thank you

**Comment by chillancezen** [comment]
hi @shariaty59 
the full list of supported proposal algorithms are:
```
                                         "null-md5", "null-sha1", "null-sha256",
                                         "null-sha384", "null-sha512", "des-null",
                                         "des-md5", "des-sha1", "des-sha256",
                                         "des-sha384", "des-sha512", "3des-null",
                                         "3des-md5", "3des-sha1", "3des-sha256",
                                         "3des-sha384", "3des-sha512", "aes128-null",
                                         "aes128-md5", "aes128-sha1", "aes128-sha256",
                                         "aes128-sha384", "aes128-sha512", "aes128gcm",
                                         "aes192-null", "aes192-md5", "aes192-sha1",
                                         "aes192-sha256", "aes192-sha384", "aes192-sha512",
                                         "aes256-null", "aes256-md5", "aes256-sha1",
                                         "aes256-sha256", "aes256-sha384", "aes256-sha512",
                                         "aes256gcm", "chacha20poly1305", "aria128-null",
                                         "aria128-md5", "aria128-sha1", "aria128-sha256",
                                         "aria128-sha384", "aria128-sha512", "aria192-null",
                                         "aria192-md5", "aria192-sha1", "aria192-sha256",
                                         "aria192-sha384", "aria192-sha512", "aria256-null",
                                         "aria256-md5", "aria256-sha1", "aria256-sha256",
                                         "aria256-sha384", "aria256-sha512", "seed-null",
                                         "seed-md5", "seed-sha1", "seed-sha256",
                                         "seed-sha384", "seed-sha512"
```

there is already support for `phase2` in ansible upstream(`devel` branch), alas, no support for `phase1`(merging a patch is not quickly accepted these days).

if you have to use other proposals with phase2, simply installing ansible from `devel` branch source can work it around. 

we will support all supported proposals in Ansible Galaxy in the future. 

please let us know how urgent your demand is.

thanks,

**Comment by shariaty59** [comment]
@chillancezen I can manually change the proposals and wait for the next version. right now we are on ansible 2.9.0. How can I follow the news on when this is out and what version I should upgrade my ansible to once introduced?

```
ansible 2.9.0
  config file = None
  configured module search path = ['/home/ashariaty/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

**Comment by shariaty59** [comment]
@chillancezen Hi, Please advise at what ansible version all proposals will be supported. Thank you

**Comment by chillancezen** [comment]
> Please advise at what ansible version all proposals will be supported. Thank you

We will be releasing full fledged Galaxy FortiOS soon,  I will keep you updated.

thanks,
Link
