### ISSUE TITLE
system_session_ttl - Underscores are not supported as specified in the example

### ISSUE THREAD

**Issue by tlrichiec** [fortinet-solutions-cse/ansible_fgt_modules#31]
fortios_system_session_ttl_example.yml

The example shows:
        port:
         -
            end_port: "5"
            start_port: "8"

However, It will not work with underscore. It only works with hyphen. There is no error message but it will not set the ports. FortiOS is rejecting it.

Example with hyphen (Working):

[httpsd 192 - 1582112574     info] api_store_parameter[227] -- add API parameter 'port': '[ { "id": 11, "protocol": 6, "start-port": 80, "end-port": 80, "timeout": "300" } ]' (type=array)
[httpsd 192 - 1582112574     info] handle_cli_req_v2_vdom[1957] -- new CMDB API request (vdom='root',user='rich')
[httpsd 192 - 1582112574     info] api_cmdb_request_init_by_path[1360] -- new CMDB query (path='system',name='session-ttl')
[httpsd 192 - 1582112574     info] api_return_cmdb_revision[779] -- ETag check for system.session-ttl
[httpsd 192 - 1582112574     info] _api_cmdb_v2_config[1145] -- editing CLI object (append=0, auto_key=0, path=system, name=session-ttl, mkey=(null), flags=0)
[httpsd 192 - 1582112574     info] api_set_cmdb_attr[1677] -- 'default': '1800'
[httpsd 192 - 1582112574     info] api_set_cmdb_attr[1677] -- 'id': '11'
[httpsd 192 - 1582112574     info] api_set_cmdb_attr[1677] -- 'protocol': '6'
[httpsd 192 - 1582112574     info] api_set_cmdb_attr[1677] -- 'start-port': '80'
[httpsd 192 - 1582112574     info] api_set_cmdb_attr[1677] -- 'end-port': '80'
[httpsd 192 - 1582112574     info] api_set_cmdb_attr[1677] -- 'timeout': '300'

Example with hyphen (Not working) - Notice that start and end port are not set:

[httpsd 192 - 1582113014     info] api_store_parameter[227] -- add API parameter 'port': '[ { "id": 11, "protocol": 6, "start_port": 80, "end_port": 80, "timeout": "300" } ]' (type=array)
[httpsd 192 - 1582113014     info] handle_cli_req_v2_vdom[1957] -- new CMDB API request (vdom='root',user='admin')
[httpsd 192 - 1582113014     info] api_cmdb_request_init_by_path[1360] -- new CMDB query (path='system',name='session-ttl')
[httpsd 192 - 1582113014     info] api_return_cmdb_revision[779] -- ETag check for system.session-ttl
[httpsd 192 - 1582113014     info] _api_cmdb_v2_config[1145] -- editing CLI object (append=0, auto_key=0, path=system, name=session-ttl, mkey=(null), flags=0)
[httpsd 192 - 1582113014     info] api_set_cmdb_attr[1677] -- 'default': '1800'
[httpsd 192 - 1582113014     info] api_set_cmdb_attr[1677] -- 'id': '11'
[httpsd 192 - 1582113014     info] api_set_cmdb_attr[1677] -- 'protocol': '6'
[httpsd 192 - 1582113014     info] api_set_cmdb_attr[1677] -- 'timeout': '300'

**Comment by chillancezen** [comment]
triaging ...

**Comment by JieX19** [comment]
Hi @tlrichiec,

We've fixed the issue from ansible_generator. It's caused by the underscore_to_hyphen() function, if you are interested in playing with the modules yourself , the best way to avoid any future similar issues is to generate the modules using the newly updated Generator. 

We will get this covered in the newly upgraded collection.
